### ISSUE TITLE
How to edit charm notches.

### ISSUE THREAD

**Issue by phunni** [KayDeeTee/Hollow-Knight-SaveManager#12]
I've tried editing the max number of charm notches - in the hopes of increases the number of notches available.  However, it doesn't seem to make any difference - although other edits (such as extra Geo or pale ore) do successfully make it into the save file - so I'm certainly saving it properly and it's working.

Either I'm misunderstanding how to manage charm notches or it isn't possible to do what I want...?

**Comment by phunni** [comment]
bump - can this be done? Can I increase my charm notches above the normal max, or be overcharmed without being overcharmed...?

**Comment by KayDeeTee** [comment]
change max notches, and untick overcharm. make sure you have autocalculate disabled

**Comment by KayDeeTee** [comment]
Although max notches may no longer work due to changes in how saves are programmed

**Comment by slackerbob** [comment]
I can confirm that this is still an issue.

Reproducible with these steps:

1. Change Max Notches to 20
2. Uncheck overcharmed
3. Save
4. Close Save Window
5. Reopen Save Window
6. The changes made above are undone and the Equipped notches are now set to 20
