### ISSUE TITLE
[DLC2] charm "Carefree Melody"

### ISSUE THREAD

**Issue by nakami** [KayDeeTee/Hollow-Knight-SaveManager#5]
in the second DLC there is a charm with ID 39 (in the JSON-format it's charm40) called "Grimmchild" which gets replaced by a different charm called "Carefree Melody".

steps required:
- find out which flag triggers the "Carefree Melody" charm
- include it in the "Charms" tab
- optional: find out whether there are other dependencies (e.g. gotCharm_40=true)

suggested approach:
- do a diff on pre- and post-aquisition

**Comment by nakami** [comment]
#6 solves this; please review and merge

**Comment by KayDeeTee** [comment]
merged
